### ISSUE TITLE
Possibly replace "nets" dependency with "node-fetch"

### ISSUE THREAD

**Issue by heapwolf** [dat-ecosystem-archive/dat-link-resolve#10]
This module uses `nets` as a dependency which uses `request` under the hood. `request` is pretty bloated and clunky, (I also noticed it's trying to do something with Coffeescript, which is pretty much obsolete). Also, it's XHR based, how would people fee about updating this dep to `node-fetch` using something like [`isomorphic-fetch`](https://github.com/matthew-andrews/isomorphic-fetch)? Fetch is standard and supported everywhere dat would be used.

**Comment by joehand** [comment]
Yes, that'd be great! Want to do a pr? I've been using [got](https://www.npmjs.com/package/got) instead of request recently ([comparison here](https://github.com/sindresorhus/got#comparison)) and that is already a dependency in dat (via `update-notifier`). We could probably go upstream and replace `request` with `got` in `nets` =)

**Comment by joehand** [comment]
I looked at the dependency tree a bit more (https://twitter.com/dat_project/status/1032326364240609280). Since we require nets elsewhere, seems like replacing request in there is the way to go. Let me know if you'd be interested otherwise I can give it a go.

**Comment by heapwolf** [comment]
@joehand sorry for the late response, just got to github-inbox zero. i can def do a PR this week.

**Comment by joehand** [comment]
https://github.com/datproject/dat-link-resolve/pull/12
